---

- hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
  - name: create foreman location
    foreman_location:
      username: "{{ sat_user }}"
      password: "{{ sat_password }}"
      server_url: https://{{ sat_url }}
      name: test_location
      organizations:
      - pharriso
      state: present
